[package]
name = "em-as-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "em_as_net"
crate-type = ["lib"]

[dependencies]
heapless = { version = "0.8.0", default-features = false }
libc = { version = "0.2.139", default-features = false }
static_cell = { version = "2.1.0", default-features = false }
# Error handling
thiserror-no-std = { version = "2.0.2", default-features = false }
anyhow = { version = "1.0.68", default-features = false }
# URL
url = { version = "2.3.1", default-features = false }
# TCP
tokio = { version = "1.39.2", features = [
    "macros",
    "rt-multi-thread",
], optional = true }
embassy-net = { version = "0.4.0", features = [
    "tcp",
    "medium-ethernet",
    "dhcpv4",
    "proto-ipv6",
] }
embedded-io-async = "0.6.1"
embedded-io-adapters = "0.6.1"
# DNS
embedded-nal-async = "0.7.1"
# TLS
rustls = { version = "0.23.12", default-features = false, features = ["tls12"] }
tokio-rustls = { version = "0.26.0", optional = true }
# Web Socket
embedded-websocket = { git = "https://github.com/LimpidCrypto/embedded-websocket", branch = "update-dep-and-embedded-io-async", features = [
    "embedded-io-async",
], optional = true }
# JSON-RPC
reqwless = "0.12.1"
webpki-roots = { version = "0.26.3", optional = true }
rand_core = "0.6.4"
strum_macros = "0.26.4"


# strum_macros = { version = "0.26.4", default-features = false }
# async-std = { version = "1.12.0", features = [
#     "attributes",
#     "tokio1",
# ], default-features = false, optional = true }
# tokio-util = { version = "0.7.7", optional = true }
# bytes = { version = "1.4.0", default-features = false }
# pin-project-lite = "0.2.9"
# embassy-net-driver = "0.2.0"
# embassy-futures = "0.1.1"
# embassy-time = "0.3.1"
# futures = { version = "0.3.25", default-features = false }
# rand = { version = "0.8.5", default-features = false, features = ["getrandom"] }
# rand_core = { version = "0.6.4", default-features = false }

[dev-dependencies]
rand = "0.8.5"
tokio = { version = "1.27.0", features = ["full"] }

[features]
default = [
    "std",
    "tcp",
    "dns",
    "tls",
    "websocket",
    "json-rpc",
] # TODO: Add tls as soon as it's working
tcp = []
dns = ["embassy-net/dns"]
tls = []
websocket = []
json-rpc = []
std = [
    "dep:tokio",
    "embedded-io-adapters/tokio-1",
    "embedded-websocket/std",
    "tokio-rustls",
    "webpki-roots",
]
webpki-roots = ["dep:webpki-roots"]
